export default {
    GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
    SWITCH_TOGGLE:'SWITCH_TOGGLE',
    GET_SWITCH:'GET_SWITCH',
    SEND_CURRENT_DAT:'SEND_CURRENT_DAT',
    UPDATE_LOCATION:'UPDATE_LOCATION',
    GET_REQUEST_INFO:'GET_REQUEST_INFO',
    GET_ALL:'GET_ALL',
    CONFIRM_REQUEST:'CONFIRM_REQUEST',
    SEND_DELIVERED:'SEND_DELIVERED',
    GET_LOCATION_DATA:'GET_LOCATION_DATA',
    SEND_ACTIVE:'SEND_ACTIVE',
    CONFIRM_PENDING_REQUEST:'CONFIRM_PENDING_REQUEST',
    SHOW_REQUEST:'SHOW_REQUEST',
    SEND_EMAIL:'SEND_EMAIL'
}