export default {
  GET_LOGIN_INPUT: 'GET_LOGIN_INPUT',
  INPUT_ERROR: 'INPUT_ERROR',
  USER_LOADING: 'USER_LOADING',
  SAVE_TOKEN:'SAVE_TOKEN',
  REMOVE_TOKEN:'REMOVE_TOKEN',
  GET_TOKEN:'GET_TOKEN',
  
};
